const asyncHandler = require('../utils/asyncHandler')
const { getAnalytics, getInsights } = require('../analytics/analyticsService')
const PDFDocument = require('pdfkit')

exports.analytics = asyncHandler(async (req, res) => {
  res.json(await getAnalytics())
})

exports.insights = asyncHandler(async (req, res) => {
  res.json({ insights: await getInsights() })
})

exports.exportPdf = asyncHandler(async (req, res) => {
  const analytics = await getAnalytics()
  const insights = await getInsights()
  const totalRevenue = analytics.monthlyData.reduce((sum, row) => sum + Number(row.revenue || 0), 0)
  const totalCollected = analytics.monthlyData.reduce((sum, row) => sum + Number(row.collected || 0), 0)
  const outstanding = totalRevenue - totalCollected
  const collectionRate = totalRevenue > 0 ? Math.round((totalCollected / totalRevenue) * 100) : 0

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename="vendorflow-report-${Date.now()}.pdf"`)

  const doc = new PDFDocument({ margin: 48, size: 'A4' })
  doc.pipe(res)

  doc.fontSize(24).fillColor('#111827').text('VendorFlow Business Report')
  doc.moveDown(0.4).fontSize(10).fillColor('#6b7280').text(`Generated on ${new Date().toLocaleString('en-IN')}`)
  doc.moveDown(1.5)

  doc.fontSize(14).fillColor('#111827').text('Financial Summary')
  doc.moveDown(0.5)
  const summary = [
    ['Total Revenue', `Rs. ${totalRevenue.toLocaleString('en-IN')}`],
    ['Collected', `Rs. ${totalCollected.toLocaleString('en-IN')}`],
    ['Outstanding', `Rs. ${outstanding.toLocaleString('en-IN')}`],
    ['Collection Rate', `${collectionRate}%`],
  ]
  summary.forEach(([label, value]) => {
    doc.fontSize(11).fillColor('#374151').text(label, { continued: true, width: 220 })
    doc.fillColor('#111827').text(value)
  })

  doc.moveDown(1.2).fontSize(14).fillColor('#111827').text('Monthly Revenue vs Collected')
  doc.moveDown(0.5)
  analytics.monthlyData.forEach((row) => {
    doc.fontSize(10).fillColor('#374151')
      .text(`${row.month}: Revenue Rs. ${Number(row.revenue || 0).toLocaleString('en-IN')} | Collected Rs. ${Number(row.collected || 0).toLocaleString('en-IN')} | Orders ${row.orders || 0}`)
  })

  doc.moveDown(1.2).fontSize(14).fillColor('#111827').text('Top Customers')
  doc.moveDown(0.5)
  if (analytics.topCustomers.length === 0) {
    doc.fontSize(10).fillColor('#6b7280').text('No customer spend data available.')
  } else {
    analytics.topCustomers.forEach((customer, index) => {
      doc.fontSize(10).fillColor('#374151')
        .text(`${index + 1}. ${customer.name} - Rs. ${Number(customer.value || 0).toLocaleString('en-IN')} (${customer.orders} orders)`)
    })
  }

  doc.moveDown(1.2).fontSize(14).fillColor('#111827').text('Order Status Distribution')
  doc.moveDown(0.5)
  if (analytics.statusBreakdown.length === 0) {
    doc.fontSize(10).fillColor('#6b7280').text('No orders found.')
  } else {
    analytics.statusBreakdown.forEach((status) => {
      doc.fontSize(10).fillColor('#374151').text(`${status.label}: ${status.count} orders (${status.pct}%)`)
    })
  }

  doc.moveDown(1.2).fontSize(14).fillColor('#111827').text('Smart Insights')
  doc.moveDown(0.5)
  insights.forEach((insight) => {
    doc.fontSize(10).fillColor('#374151').text(`- ${insight}`)
  })

  doc.moveDown(2).fontSize(9).fillColor('#6b7280').text('Generated by VendorFlow', { align: 'center' })
  doc.end()
})
